Blog0190/Controllers/SiteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Blog0190.Models.Sinifler;

namespace Blog0190.Controllers
{
    public class SiteController : Controller
    {
        Context c = new Context();
      
        // GET: Site

        public ActionResult Home()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Blog()
        {
            var bloglar = c.Blogs.ToList();
            return View(bloglar);
        }
        [HttpPost]
        public ActionResult Blog(string TextName, Blog blo)
        {
            var blogSiyahisi = c.Blogs.Where(p => p.TextName.Contains(TextName)).ToList();
            return View(blogSiyahisi);
        }

        public ActionResult BlogDetay(int id)
        {
            var blogbul = c.Blogs.Where(x => x.BlogID == id).ToList();
            return View(blogbul);
           
        }
        public ActionResult blogcommentlerigoster(int id)
        {
            var blogbul = c.BlogComments.Where(x => x.BlogID == id).ToList();
            return View(blogbul);
        }
        
        public PartialViewResult LessonSiyahisi2()
        {
            var deyer = c.Lessons.ToList();
            return PartialView(deyer);
        }
        
        public PartialViewResult BlogSiyahisi2()
        {
            var deyer = c.Blogs.ToList();
            return PartialView(deyer);
        }
        //----------------------------------
        [HttpGet]
        public PartialViewResult BlogInTheHome()
        {
            var bloglar = c.Blogs.ToList();
            return PartialView(bloglar);
        }
        [HttpPost]
        public PartialViewResult BlogInTheHome(string TextName, Blog blo)
        {
            var blogSiyahisi = c.Blogs.Where(p => p.TextName.Contains(TextName)).ToList();
            return PartialView(blogSiyahisi);
        }
        //-----------------------------------
        public PartialViewResult LessonInTheHome()
        {
            var lesson = c.Lessons.ToList();
            return PartialView(lesson);
        }
        public PartialViewResult AboutInTheHome()
        {
            var about = c.Abouts.ToList();
            return PartialView(about);
        }
        public ActionResult Lesson()
        {
            var lesson = c.Lessons.ToList();
            return View(lesson);
            
        }
        [HttpPost]
        public ActionResult Lesson(string TextName, LessonInformation blo)
        {
            var less = c.Lessons.Where(p => p.TextName.Contains(TextName)).ToList();
            return View(less);
        }

        public ActionResult LessonDetay( int id)
        {
            var lessonbul = c.Lessons.Where(x => x.LessonID == id).ToList();
            
            return View(lessonbul);
        }
        public ActionResult lessoncommentlerigoster(int id)
        {
            var lessons = c.LessonComments.Where(x => x.LessonID == id).ToList();
            return View(lessons);
        }
        public ActionResult Foto()
        {
            var fotoinformation = c.Fotos.ToList();
            return View(fotoinformation);
        }
        public ActionResult About()
        {
            var deyerler = c.Abouts.ToList();
            return View(deyerler);
        }
        public ActionResult Contact()
        {
            var aboutlocation = c.Abouts.ToList();
            return View(aboutlocation);
        }
        public PartialViewResult PageKecid()
        {
            return PartialView();
        }
        //---------------------------------------------
        IEnumerableClass iemc = new IEnumerableClass();
        public PartialViewResult FooterLayout()
        {
            iemc.AddresDeyer = c.AddresInformations.ToList();
            iemc.ContactDeyer = c.Contacts.ToList();
            iemc.AboutDeyer = c.Abouts.ToList();
            return PartialView(iemc);
        }
        public PartialViewResult TopLayout()
        {
            iemc.AddresDeyer = c.AddresInformations.ToList();
            return PartialView(iemc);
        }
        public PartialViewResult AdressLayout()
        {
            return PartialView();
        }
        //---------------------------------------------------
        // bloga yorum yazmag prosesleri
    
        [HttpGet]
        public PartialViewResult BlogYorumYaz(int id)
        {
            ViewBag.deyer = id;
            return PartialView();
        }
        [HttpPost]
        public PartialViewResult BlogYorumYaz(BlogComment y)
        {
            c.BlogComments.Add(y);
            c.SaveChanges();
            return PartialView();
        }
        //----------------------------------------
        //Lesson a Yorum yazmag prosesi
        [HttpGet]
        public PartialViewResult LessonYorumYaz(int id)
        {
            ViewBag.deyer = id;
            return PartialView();
        }
        [HttpPost]
        public PartialViewResult LessonYorumYaz(LessonComment ly)
        {
            c.LessonComments.Add(ly);
            c.SaveChanges();
            return PartialView();
        }
        // Contact seifesinden mesaj gondermek
        //-------------------------------------------
        

        [HttpGet]
        public PartialViewResult ContactSeifesindenMesajGonder()
        {
            return PartialView();
        }
        [HttpPost]
        public PartialViewResult ContactSeifesindenMesajGonder(Contact contact)
        {
            c.Contacts.Add(contact);
            c.SaveChanges();
            return PartialView();
        }
        //-----------------------------------------
        //Service information
        public ActionResult Service()
        {
            var service = c.services.ToList();
            return View(service);
        }
        [HttpPost]
        public ActionResult Service(string TextName, ServiceInformation blo)
        {
            var servis = c.services.Where(p => p.ServicesName.Contains(TextName)).ToList();
            return View(servis);
        }
        public PartialViewResult AxdarishSistemi()
        {
            return PartialView();
        }
    }
}

Blog0190/Views/Shared/_AdminLayout.cshtml
@{
    Layout = null;
}

<html>
<head>
<title>W3.CSS</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link href="~/Content/bootstrap.min.css" rel="stylesheet" />
</head>
<body>

    <!-- Sidebar -->
    <div class="w3-sidebar w3-light-grey w3-bar-block" style="width: 9%; color:red;">
        <h3 class="w3-bar-item">Menu</h3>
        <a href="/Admin/Blog/" class="w3-bar-item w3-button">Blog</a>
        <a href="/Admin/BLogComment/" class="w3-bar-item w3-button">Blog Comment</a>
        <a href="/Admin/Lesson/" class="w3-bar-item w3-button">Lesson</a>
        <a href="/Admin/LessonComment/" class="w3-bar-item w3-button">Lesson Comment</a>
        <a href="/Admin/About/" class="w3-bar-item w3-button">About</a>
        <a href="/Admin/AddressInformation/" class="w3-bar-item w3-button">Address</a>
        <a href="/Admin/Foto/" class="w3-bar-item w3-button">Foto</a>
        <a href="/Admin/Admin/" class="w3-bar-item w3-button">Admin</a>
        <a href="/Admin/Service/" class="w3-bar-item w3-button">Service</a>
        <a href="/Admin/Contact/" class="w3-bar-item w3-button">Contact</a>
        <a href="/Site/Home/" class="w3-bar-item w3-button">Sayta Kec</a>
        <a href="/Admin/LogOut/" class="w3-bar-item w3-button" style="color:orangered;">Login</a>
    </div>

    <!-- Page Content -->
    <div style="margin-left:9%">

        <div class="w3-container w3-teal">
            <h1>www.dadashaliyev.com Saytinin Admin Paneli </h1>
        </div>

       @RenderBody()

        

    </div>

</body>
</html>

Blog0190/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Blog0190/Views/Shared/_MyLayout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>Dadash Aliyev</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="Free HTML Templates" name="keywords">
    <meta content="Free HTML Templates" name="description">

    <!-- Favicon -->
    <link href="~/free-travel-website-template/img/favicon.ico" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700&display=swap" rel="stylesheet">

    <!-- Font Awesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="~/free-travel-website-template/lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">
    <link href="~/free-travel-website-template/lib/tempusdominus/css/tempusdominus-bootstrap-4.min.css" rel="stylesheet" />

    <!-- Customized Bootstrap Stylesheet -->
    <link href="~/free-travel-website-template/css/style.css" rel="stylesheet">
</head>

<body>
    <!-- Topbar Start -->
    @Html.Action("TopLayout", "Site")

    <!-- Topbar End -->
    <!-- Navbar Start -->
    <div class="container-fluid position-relative nav-bar p-0">
        <div class="container-lg position-relative p-0 px-lg-3" style="z-index: 9;">
            <nav class="navbar navbar-expand-lg bg-light navbar-light shadow-lg py-3 py-lg-0 pl-3 pl-lg-5">
                <a href="" class="navbar-brand">
                    @*<h1 class="m-0 text-primary"><span class="text-dark"></span>Techno</h1>*@
                    <img src="~/free-travel-website-template/img/yaqubinfo_logo555-removebg-preview.png" width="150px" height="100px" alt="">
                </a>
                <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse justify-content-between px-3" id="navbarCollapse">
                    <div class="navbar-nav ml-auto py-0">

                        <a href="/Site/Home/" class="nav-item nav-link">Home</a>
                        <a href="/Site/About/" class="nav-item nav-link">About</a>
                        <a href="/Site/Foto/" class="nav-item nav-link">Foto</a>
                        @*<div class="nav-item dropdown">
            <a href="#" class="nav-link dropdown-toggle " data-toggle="dropdown">Blog</a>
            <div class="dropdown-menu border-0 rounded-0 m-0">
                <a href="/Site/Blog/" class="dropdown-item ">Blog</a>
            </div>
        </div>*@
                        <a href="/Site/Blog/" class="nav-item nav-link">Blog</a>
                        <a href="/Site/Lesson/" class="nav-item nav-link">Lesson</a>
                        <a href="/Site/Service/" class="nav-item nav-link">Service</a>
                        <a href="/Site/Contact/" class="nav-item nav-link">Contact</a>


                    </div>
                </div>
            </nav>
        </div>
    </div>
    <!-- Navbar End -->
    <!-- Header Start -->
    <div class="container-fluid page-header">
        <div class="container">
            <div class="d-flex flex-column align-items-center justify-content-center" style="min-height: 400px">
                <h3 class="display-4 text-white text-uppercase">Yaqub Info</h3>

                <div class="d-inline-flex text-white">
                    <p class="m-0 text-uppercase"><a class="text-white" href="/Site/About/">Developer Xidmeti</a></p>

                </div>
            </div>
        </div>
    </div>

    <br />
    <div class="w-100">
        <form id="formSearch" method="post">

            <div class="input-group">
                <input type="text" class="form-control border-light" style="padding: 25px; width:300px;" id="TextName" name="TextName" placeholder="Search write">
                <div class="input-group-append">
                    <button class="btn btn-primary px-3" type="submit" id="submitsearch" value="Search">Search</button>
                </div>
            </div>

        </form>
    </div>

    <!-- Header End -->
    <!-- Booking Start -->
    <!-- Booking End -->
    <!-- Blog Start -->
    @RenderBody()
    <!-- Blog End -->
    <!-- Footer Start -->
    @Html.Action("FooterLayout", "Site")
    <div class="container-fluid bg-dark text-white border-top py-4 px-sm-3 px-md-5" style="border-color: rgba(256, 256, 256, .1) !important;">
        <div class="row">
            <div class="col-lg-6 text-center text-md-left mb-3 mb-md-0">
                <p class="m-0 text-white-50">
                    Copyright &copy; <a href="#">Domain</a>. All Rights Reserved.</a>
                </p>
            </div>
            <div class="col-lg-6 text-center text-md-right">
                <p class="m-0 text-white-50">
                    Designed by <a href="https://htmlcodex.com">HTML Codex</a>
                </p>
            </div>
        </div>
    </div>
    <!-- Footer End -->
    <!-- Back to Top -->
    <a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="fa fa-angle-double-up"></i></a>


    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
    <script src="lib/easing/easing.min.js"></script>
    <script src="lib/owlcarousel/owl.carousel.min.js"></script>
    <script src="lib/tempusdominus/js/moment.min.js"></script>
    <script src="lib/tempusdominus/js/moment-timezone.min.js"></script>
    <script src="lib/tempusdominus/js/tempusdominus-bootstrap-4.min.js"></script>

    <!-- Contact Javascript File -->
    <script src="mail/jqBootstrapValidation.min.js"></script>
    <script src="mail/contact.js"></script>

    <!-- Template Javascript -->
    <script src="js/main.js"></script>
</body>

</html>